# SPDX-License-Identifier: GPL-2.0
# UFSHCD makefile
obj-$(CONFIG_SCSI_UFSHCD_VIVO) += ufshcd-vivo-core.o
ufshcd-vivo-core-y += ufs-sysfs.o ufs-qcom.o ufshcd-pltfrm.o ufs_bsg.o ufshcd-crypto.o ufshcd-crypto-qti.o ufs_ven.o ufshcd.o
